# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 964e91f72690ccb13478d15b0b3997bfafe99bee67e05672a0fd5cc32f46cab25229d355ea3a1a4e5609d8f7e425a012008676eb821b30b419a20060c05640d0

test:
  secret_key_base: 8ba4a1a43c1beab6d7907593dd009564c623f954e0bce22109559677ef35bc27262fb21459d776ffa43fd588671c75819620a549e94ce56e1a99883af93196bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
